PDC&&PDC.mark("c_jl");
(function(m,l,h,g){function e(E){var i,u,a,b,d,c;i=z[E];if(!i)throw Error('Requiring unknown module "'+E+'"');if(i.hasOwnProperty("exports"))return i.exports;i.exports=E={};u=i.deps;c=u.length;d=-1;for(b=[];++d<c;)a=u[d],b.push("module"===a?i:"exports"===a?E:e(a));if((u=i.factory.apply(null,b))!==g)i.exports=E=u;return E}function a(a,i,u){i=["global","require","module","exports"].concat(i);z[a]={factory:u,deps:i}}function f(a,i,u){var b=Array.prototype.slice;f=function(i,a,E){var u=b.call(arguments,
1);return b.apply(i,u)};return f.apply(this,f(arguments,0))}function c(a,i){i=i||h;return i.getElementById(a)}function d(a){for(var a=a||{},i=arguments,u=i.length,b=0,d,c;++b<u;)for(c in d=i[b],d)d.hasOwnProperty(c)&&(a[c]=d[c]);return a}function b(a,i,u){var c;this instanceof b?(this.constructor=a,d(this,u)):(c=b.prototype,b.prototype=i.prototype,a.prototype=new b(a,i,u),b.prototype=c)}function j(){function a(){for(var c=-1,d;++c<b;)d=i[c],d[0].apply(d[1],d[2]),delete i[c];i=[];b=0;u=null}var i=
[],u=null,b=0;j=function(c,d,e){if(!c)return j;i.push([c,d||this,f(arguments,2)]);b++;null===u&&(u=setTimeout(a,0));return u};return j.apply(this,f(arguments,0))}function k(a){var i,b=h.getElementsByTagName("head");i=b.length&&b[0]||h.body;k=function(a){i.appendChild(a)};return k(a)}function o(a,i){var b=D(a)?[]:{};"function"!=typeof i&&(i=i===g?function(a,i){return!!i}:function(a,b){return b==i});p(a,function(a,c){i(a,c)&&(b[a]=c)});return b}function A(a,b,c){var d,f;d=h.createElement(a);f=d.style;
b&&p(b,function(a,b){d[a]=b});f&&c&&p(c,function(a,b){f[a]=b});return d}function p(a,b){v(a,function(a,c){b(a,c);return!1})}function v(a,b){var c;c=a.length;return(c===g||s(a)?function(a,b){for(var c in a)if(a.hasOwnProperty(c)&&b(c,a[c]))return!0;return!1}:function(a,b){var i;for(i=0;i<c;i++)if(b(i,a[i]))return!0;return!1})(a,b)}function q(a){for(var b="Boolean,Number,String,Function,Array,Date,RegExp,Object".split(","),c=b.length,d=Object.prototype.toString,f={},e;c--;)e=b[c],f["[object "+e+"]"]=
e.toLowerCase();q=function(a){return null==a?""+a:f[d.call(a)]||"object"};return q(a)}function s(a){return"function"===q(a)}function D(a){function b(a){return"array"===q(a)}D=Array.isArray||b;return D(a)}function s(a){return"[object Function]"==Object.prototype.toString.call(a)}function B(a,b){return n(a,b,f(arguments,2))}function n(a,b,c){y.push([a,b,c]);if(!t){for(t=!0;a=y.length;){for(b=0;b<a;b++)c=y[b],c[0].apply(c[1],c[2]);y.splice(0,a)}t=!1}}function H(a,b){var c=[],d=a.length;if("function"!==
typeof b)return a;for(;d--;)c.unshift(b(a[d]));return c}var z={};z.global={exports:m};z.require={exports:e};var C={addHandler:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c},getEvent:function(a){return a?a:l.event},getTarget:function(a){return a.target||a.srcElement},preventDefault:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},removeHandler:function(a,
b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent?a.detachEvent("on"+b,c):a["on"+b]=null}},y=[],t=!1;a("Arbiter",["global","ErrorUtils"],function(a,b){function c(a){this._listenerMap={};this._setup(a||[])}var a=b("global"),e=b("ErrorUtils");d(c.prototype,{_setup:function(a){for(var b=a.length,c=this._listenerMap;b--;)c[a[b]]={args:null,cbs:[]}},on:function(b,c,d){var i=this._listenerMap[b],e,w;if(!i)return!1;d=d||a;e=f(arguments,3);(w=i.args)?n(c,d,e.concat(w)):i.cbs.push([c,
d,e]);return!0},done:function(a,b){var c=this._listenerMap[a],d,i,w;if(!c)return!0;i=c.cbs;w=i.length;b=f(arguments,1);c.args=b;d=this.emit.apply(this,arguments);c.cbs=i.slice(w);return d},emit:function(a,b){var c=this._listenerMap[a],d,i,w;if(!c)throw Error(a+" has not listened");b=f(arguments,1);c=c.cbs;d=c.length;i=-1;for(w=!0;++i<d;){var r;r=c[i];var x=b,I=r[0],g=r[1],x=r[2].concat(x);r=e.inGuard()?I.apply(g,x):e.applyWithGuard(I,g,x);w=!1!==r&&w}return!!w},undo:function(a){a=this._listenerMap[a];
if(!a)return!1;a.args=null}});return c});a("Resource",["Arbiter","CSSLoader","JSLoader"],function(a,c){function f(a,b){if(this instanceof f)h.call(this,r),this.id=a,this.deps=b,this.loaded=!1,this.state=x;else return e(a)}function e(a){var b,c;if(!(b=k[a]))throw Error('resource "'+a+'" unknow.');if(!(c=b._handler))c=b._handler=new f(a,b.deps||[]),b._loaded&&(c.loaded=!0);return c}function j(a,b){F[a]=b}function n(a,b){var c;if(b!==g)c=k[a]||{},d(c,b),k[a]=c;else for(a in b=a,b)n(a,b[a])}var h=c("Arbiter"),
k={},F={},w={},r=["load","resolve"],x=1;b(f,h,{load:function(){function a(){--d||(x=!0,e&&this.done("resolve"))}function b(){e=!0;this.done("load");x&&this.done("resolve")}var c,d,r,w,i,e,x;if(2<=this.state)return!1;this.state=2;e=this.loaded;x=!0;c=this.deps;r=d=c.length;if(0<r){x=!1;for(w=-1;++w<r;)i=f(c[w]),i.on("resolve",a,this),i.load()}B(function(){var a;if(e)B(b,this);else{a=this.id;var c,d,r;c=k[a];d=c.type;if(!(r=F[d]))throw Error('unknow type "'+d+'"');a=new r(a,c);a.on("load",b,this);a.load()}},
this)}});d(f,{setResourceMap:n,setModuleMap:function(a){d(w,a)},setResourceLoaded:function(a){var b;for(b=a.length;b--;)n(a[b],{_loaded:!0})},moudelToResource:function(a){var b=w[a];if(!b)throw Error('module "'+a+'" unknow.');return e(b)}});j("css",c("CSSLoader"));j("js",c("JSLoader"));return f});a("Pagelet",["Arbiter","Resource"],function(a,i){function f(a){if(this instanceof f)e.call(this,n),this.id=a,this.root=null===a,this.state=k;else{var b;if(null===a)return new f(a);b=h[a];b||(b=new f(a),h[a]=
b);return b}}var e=i("Arbiter"),g=i("Resource"),n="arrive,beforeload,cssresolved,jsresolved,beforedisplay,display,load,afterload,resolved,beforeunload,unload,afterunload".split(","),k=0,h={},F={};b(f,e,{arrive:function(a){d(this,{html:a.html||"",css:a.css||[],js:a.js||[],parent:a.parent?f(a.parent):null,children:a.children||[],state:1});this.afterload=!1;this.done("arrive");this.emit("beforeload")?this.load():(this.afterload=!0,this.done("afterload"))},load:function(){function a(){this.parent.on("display",
b,this)}function b(){this.emit("beforedisplay")&&this.display()}if(2<=this.state)return!1;this.state=2;this.on("cssresolved",this.parent?a:b,this);this._resolve(this.css,"cssresolved");this._resolve(this.js,"jsresolved")},setState:function(){if(3>this.state)return!1;this.state=4;var a,b,c,d;a=this.children;b=a.length;c=-1;if(b)for(;++c<b;)d=a[c],d=f(d),d.setState()},doUnload:function(){function a(){--b||this.emit("beforeunload")&&this.unload()}var b,c,d,i,e;c=this.children;d=b=c.length;i=-1;if(d)for(;++i<
d;)e=c[i],e=f(e),e.on("unload",a,this),e.doUnload();else this.emit("beforeunload")&&this.unload()},remove:function(){if(4==this.state)return!1;this.setState();this.on("unload",this.destroy,this);this.doUnload()},unload:function(){this.done("unload")},destroy:function(){var a,b,c,d;a=this.children;b=a.length;c=-1;if(b)for(;++c<b;)d=a[c],d=f(d),d.destroy();delete h[this.id];this.state=k;j(this.done,this,"afterunload")},isUnloading:function(){return 4==this.state},_resolve:function(a,b){function c(){--d||
this.done(b)}var d,f,i,e;f=d=a.length;i=-1;if(f)for(;++i<f;)e=g(a[i]),e.on("resolve",c,this),e.load();else this.done(b)},display:function(){if(3<=this.state)return!1;this.state=3;this.root||(c(this.id).innerHTML=this.html);this.done("display");this.on("jsresolved",function(){this.done("load");this.afterload||this.done("afterload")},this)},get:function(a,b){return F[a]||b},set:function(a,b){F[a]=b}});d(f,{hasPagelet:function(a){return!!h[a]}});return f});a("BigPipe",["Resource","Emulator","Arbiter",
"Requestor"],function(a,c){function d(){g.call(this);this.hooks={}}var f=c("Resource"),e=c("Emulator"),g=c("Arbiter"),n=c("Requestor"),j=!1;b(d,g,{init:function(a){if(j)throw Error("BigPipe has been initialized.");j=!0;this.emulator=e();this.emulator.listen();this.emulator.on("request",this.request,this);this.requestor=new n(a)},onPageletArrive:function(a){var b=a.callback,c,d,e,i,g,n,j=this.hooks;if(b){c=a.hook||{};for(var h in b){d=b[h];e=-1;i=d.length;for(g=c[h]||[];++e<i;)n=d[e],g.push(j[n]),
delete j[n];c[h]=g}a.hook=c}f.setResourceMap(a.map||{});f.setModuleMap(a.mods||{});this.requestor.arrive(a)},request:function(a,b){this.requestor.request(a,b)},sessionStart:function(a){this.requestor.start(a)},sessionEnd:function(a){this.requestor.end(a)},loadModule:function(a,b){var c=f.moudelToResource(a);c.on("resolve",b);c.load()},loadedResource:function(a){f.setResourceLoaded(a)},log:function(){}});return d});a("CSSLoader",["Arbiter"],function(a,c){function d(a,b){r.call(this,x);this.id=a;this.url=
b.src;this.state=H}function f(a){y||(y=h.createElement("meta"),k(y));t=a||t;y.className=t.join(" ")}function e(a){return!a?!1:(a=l.getComputedStyle?getComputedStyle(a,null):a.currentStyle)&&1<parseInt(a.height,10)}function g(){var a,b,c,d,i,n,r,j,x,h,k,l;b=2<t.length?e(y):!0;c=0;d=[];i=!1;n=+new Date;for(a in p){r=p[a];j=r[0];x=!1;b&&e(j)&&(x=!0);for(k=1,h=r.length;k<h;k++)l=r[k],x?l[1].call(l[2],!0):l[0]<n&&(l[1].call(l[2],!1),r.splice(k,1),k--,h--);x||1==h?(j.parentNode.removeChild(j),delete p[a],
i=!0):(d.push("css_"+a),c++)}c?(i&&f(d),setTimeout(g,20)):(t=[],y&&(y.parentNode.removeChild(y),y=null),s=!1)}function n(a,b,c,d){var e,i;if(!(e=p[a]))i="css_"+a,e=h.createElement("meta"),e.className=i,k(e),e=[e],p[a]=e,t.push(i),f();b=+new Date+b;e.push([b,c,d]);s||(s=!0,j(g))}function z(a){this.state=a?m:v;this.done("load",a)}function B(){var a=this.id,b=this.url,c=h.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=b;k(c);n(a,C,z,this)}function w(){for(var a=this.id,b=this.url,
c=q.length,d=c,e;d--;)if(31>q[d].length){e=o[d];break}0>d&&(e=h.createStyleSheet(),o.push(e),q.push([]),d=c);e.addImport(b);q[d].push(b);n(a,C,z,this)}var r=c("Arbiter"),x=["load"],H=1,m=3,v=4,C=5E3,s=!1,q=[],o=[],p={},t=[],y=null;b(d,r,{load:function(){2>this.state&&(this.state=2,this._load())},_load:h.createStyleSheet?w:B});return d});a("JSLoader",["Arbiter"],function(a,c){function d(a,b){e.call(this,f);this.id=a;this.url=b.src;this.state=n}var e=c("Arbiter"),f=["load"],n=1,z=3,B=4;b(d,e,{load:function(){function a(f){if(!(b.state>=
z)){b.state=f?z:B;b.done("load");l[c]=d;if(d===g)try{delete l[c]}catch(i){}j(function(){e.onerror=null;e.parentNode&&e.parentNode.removeChild(e);e=null})}}var b=this,c,d;if(!(2<=this.state)){this.state=2;var e=h.createElement("script");e.src=this.url;e.async=!0;e.onerror=function(){a(!1)};c="js_"+this.id;d=l[c];l[c]=a;k(e)}}});return d});a("Emulator",["Arbiter"],function(a,c){function d(a){var b=!1;if(a&&(a=(""+a).replace(/(^\s*)|(\s*$)/g,"")))b=o(a.split(" "),function(a,b){return!!(""+b).replace(/(^\s*)|(\s*$)/g,
"")});return b}function e(a){var b,c;for(b="A";a&&a.nodeName!=b;)a=a.parentNode;if(!a)return!1;if(!this.emit("beforetrigger",a))return!0;b=a.href;if(!b)return!1;var f=!1,i=/^\s*(https?|ftp):\/\//i;b==j||0==b.indexOf(j+"/")?f=b.substring(k)||"/":i.test(b)||(f=b);b=f;if(!b)return!1;(a=a.rel)&&(c=d(a));if(!c)return!1;this.emit("request",b,c);return!0}function f(){if(this instanceof f)n.call(this,l);else return g||(g=new f),g}var n=c("Arbiter"),g,j,k,l=["beforetrigger","request"];j=[location.protocol,
"//",location.host].join("");k=j.length;b(f,n,{listen:function(){var a=this;C.addHandler(h.documentElement,"click",function(b){var c,b=C.getEvent(b);c=C.getTarget(b);e.call(a,c)&&C.preventDefault(b)})}});return f});a("Requestor",["Arbiter","Controller"],function(a,c){function e(a){f.call(this,g);d(this,{ajaxKey:a.ajaxKey,separator:a.separator,sessionKey:a.sessionKey});k||this.init()}var f=c("Arbiter"),n=c("Controller"),g=["arrive","allarrived"],j={},k=!1,l=!1,z=0;b(e,f,{init:function(){k=!0;this.sessionState=
this.state=0;this.controller=new n;this.controller.on("arrived",this._onItemArrived,this);this.on("allarrived",this._onSessionEnd,this);this.refCount=0},start:function(a){this.sessionID=a;switch(this.sessionState){case 1:case 2:case 3:this.sessionState=2;break;case 0:this.sessionState=1}},end:function(){this.sessionState=3;0==this.refCount&&this._onSessionEnd()},arrive:function(a){var b=this.sessionID,c=this.sessionState;j[b-1]&&(j[b-1]=null);2==c||3==c?(j[b]=j[b]||[],j[b].push(a)):(++this.refCount,
this.controller.handdleArrive(a))},request:function(a,b){z++;this._ajaxRequest([a,/.*\?.*/.test(a)?"&":"?",this.ajaxKey,b?"="+b.join(this.separator):"","&",this.sessionKey,"=",z].join(""))},_onSessionEnd:function(){this.sessionState=0;var a=j[this.sessionID],b=this;a&&p(a,function(a,c){b.refCount++;b.controller.handdleArrive(c)})},_onItemArrived:function(){!--this.refCount&&3==this.sessionState&&this.emit("allarrived")},_ajaxRequest:function(a){switch(this.state){case 1:var b=this._ajaxIframe;b&&
b.parentNode&&b.parentNode.removeChild(b);this._initAjaxIframe(a);break;case 0:this._initAjaxIframe(a),this.state=1}},_initAjaxIframe:function(a){var b=this;this._ajaxIframe=A("iframe",{src:a},{display:"none"});h.body.appendChild(this._ajaxIframe);clearTimeout(l);C.addHandler(this._ajaxIframe,"load",function(){1==b.state&&(l=setTimeout(function(){var a=b._ajaxIframe;a&&a.parentNode&&a.parentNode.removeChild(a);b.state=0},100))})}});return e});a("Controller",["Arbiter","Pagelet","Resource"],function(a,
d){function e(){j.call(this,g)}function f(a,b){var d=c(a,b),e;if(!(e=d.firstChild)||8!==e.nodeType)return null;e=e.nodeValue;d.parentNode.removeChild(d);e=e.slice(1,-1);return e.replace(/--\\>/g,"--\>").replace(/\\\\/g,"\\")}var j=d("Arbiter"),n=d("Pagelet");d("Resource");var g=["arrived"];b(e,j,{handdleArrive:function(a){var b,c;c=a.id;n.hasPagelet(c)&&(b=n(c),b.remove());if(n.hasPagelet(c))if(b=n(c),b.isUnloading())b.on("afterunload",this._doArrive,this,a);else throw Error("unbeliveble");else this._doArrive(a)},
_doArrive:function(b){var c,d,e,i,j,g,k,h;c=b.id||null;d=b.content?b.content:b.container_id?f(b.container_id,b.doc):null;b.html=d;d=n(c);if(e=b.hook)for(i in e){j=e[i];k=j.length;for(g=-1;++g<k;){h=j[g];try{d.on(i,s(h)?h:new Function("pagelet",h),a,d)}catch(l){throw Error("Error on add script:"+j[g]);}}}d.arrive(b);d.on("afterload",function(a){this.emit("arrived",a)},this,c)}});return e});a("ErrorUtils",["wrapFunction"],function(a,b,c){var d;function e(a){if(!a)return[];a=a.split(/\n\n/)[0].replace(/[\(\)]|\[.*?\]|^\w+:\s.*?\n/g,
"").split("\n");return a=H(a,function(a){var b,c,d,a=a.trim();/(:(\d+)(:(\d+))?)$/.test(a)&&(c=RegExp.$2,d=RegExp.$4,a=a.slice(0,-RegExp.$1.length));if(C.test(a)||/(.*)(@|\s)[^\s]+$/.test(a))a=a.substring(RegExp.$1.length+1),b=/(at)?\s*(.*)([^\s]+|$)/.test(RegExp.$1)?RegExp.$2:"";a={identifier:b,script:a,line:c,column:d};s&&s(a);a.text="    at"+(a.identifier?" "+a.identifier+" (":" ")+a.script+(a.line?":"+a.line:"")+(a.column?":"+a.column:"")+(a.identifier?")":"");return a})}function f(a){if(a){if(a._originalError)return a}else return{};
var b=e(a.stackTrace||a.stack),c=!1;if(a.framesToPop){for(var d=a.framesToPop,j;0<d&&0<b.length;)j=b.shift(),d--,c=!0;v.test(a.message)&&2===a.framesToPop&&j&&m.test(j.script)&&(a.message+=" at "+j.script+(j.line?":"+j.line:"")+(j.column?":"+j.column:""));delete a.framesToPop}d={line:a.lineNumber||a.line,column:a.columnNumber||a.column,name:a.name,message:a.message,type:a.type,script:a.fileName||a.sourceURL||a.script,stack:b.map(function(a){return a.text}).join("\n"),stackFrames:b,guard:a.guard,guardList:a.guardList,
extra:a.extra,snapshot:a.snapshot};"string"!==typeof d.message&&(d.messageObject=d.message,d.message=""+d.message);s&&s(d);c&&(delete d.script,delete d.line,delete d.column);b[0]&&(d.script=d.script||b[0].script,d.line=d.line||b[0].line,d.column=d.column||b[0].column);d._originalError=a;for(var i in d)null==d[i]&&delete d[i];return d}function j(a){if(G)return!1;0<t.length&&(a.guard=a.guard||t[0],a.guardList=t.slice());a=f(a);o.length>y&&o.splice(y/2,1);o.push(a);G=!0;for(var b=0;b<q.length;b++)try{q[b](a)}catch(c){}G=
!1;return!0}function n(a,b,c,e,i){t.unshift(i||h);A=!0;var g;if(d||/nocatch/.test(location.search)){try{g=a.apply(b,c||[])}finally{t.shift(),A=0!==t.length}return g}try{return g=a.apply(b,c||[])}catch(k){b=f(k),e&&e(b),a&&(b.callee=a.toString().substring(0,100)),c&&(b.args=Array.prototype.slice.call(c).toString().substring(0,100)),b.guard=t[0],b.guardList=t.slice(),j(b)}finally{t.shift(),A=0!==t.length}}function g(a,b,c){b=b||a.name||z;return function(){return n(a,c||this,arguments,null,b)}}function k(a,
b,c,d,e){e=e||{};e.message=e.message||a;e.script=e.script||b;e.line=e.line||c;e.column=e.column||d;e.guard=B;e.guardList=[B];j(e)}a=b("wrapFunction");d=void 0;var h="<anonymous guard>",z="<generated guard>",B="<window.onerror>",m=/^https?:\/\//i,v=/^Type Mismatch for/,C=/(.*?)(\s)(?:Unknown script code|Function code|eval code)$/,q=[],s,o=[],y=50,t=[],A=!1,G=!1;a.setWrapper(g,"entry");l.onerror=k;c.exports={ANONYMOUS_GUARD_TAG:h,GENERATED_GUARD_TAG:z,GLOBAL_ERROR_HANDLER_TAG:B,addListener:function(a,
b){q.push(a);b||p(o,a)},setSourceResolver:function(a){s=a},applyWithGuard:n,guard:g,history:o,inGuard:function(){return A},normalizeError:f,onerror:k,reportError:j}});a("wrapFunction",[],function(a,b,c){function d(a,b,c){b=b||"default";return function(){var a=b in fnMap?e[b](a,c):a;return a.apply(this,arguments)}}var e={};d.setWrapper=function(a,b){e[b||"default"]=a};c.exports=d});var G=e("BigPipe");m.BigPipe=new G;m.BigPipe.ErrorUtils=e("ErrorUtils")})(this,window,document);
(function(m,l){function h(a,b,c,d){var e,f,h;f=b.length;e=k[a]||{};e.name=a;e.factory=c;e.deps=b;e.flag=d||A;e.waiting=f;j[a]=e;delete k[a];for(c=0;c<f;c++)h=b[c],(d=j[h])?h=d.waiting:(d=k[h]=k[h]||{},h=!0),h?(d=d.refs=d.refs||[],d.push(a)):e.waiting--;e.waiting||g(e)}function g(a){var b=a.refs,c=a.name,d;a.flag&p&&(e(c),delete j[c]);if(b)for(c=0,d=b.length;c<d;c++)(a=j[b[c]])&&a.waiting&&(--a.waiting||g(a))}function e(a){var b,c,d,f,g,h,k;b=j[a];if(!b)throw Error('Requiring unknown module "'+a+'"');
if(b.error)throw Error('Requiring module "'+a+'" which threw an exception');if(b.waiting)throw Error('Requiring module "'+a+'" with unresolved dependencies');if(b.hasOwnProperty("exports"))return b.exports;b.exports=c={};a=b.deps;h=a.length;g=-1;for(f=[];++g<h;)d=a[g],f.push("module"===d?b:"exports"===d?c:e(d));v&&!v.inGuard()?v.applyWithGuard(function(){k=b.factory.apply(this,f);void 0!==k&&k!==c&&(b.exports=k)},this,f):(k=b.factory.apply(this,f),void 0!==k&&k!==c&&(b.exports=k));return b.exports}
function a(a,b){function c(){--j||d()}function d(){var c=[],j;for(j=0;j<f;j++)c.push(e(a[j]));b&&b.apply(this,c)}var f,j,g,k;if(j=f=a.length)for(g=0;g<f;g++)k=a[g],l.loadModule(k,c);else d()}function f(b,c){D?(h("__mod_"+q++,b,c,p),a(b)):o.push([b,c])}function c(){if(!D){D=!0;f.onready&&f.onready();var b,c,d,e;for(b=0,c=o.length;b<c;b++)d=o[b],e=d[0],d=d[1],h("__mod_"+q++,e,d,p),a(e);o=null}}function d(a,b){j[a]={exports:b,waiting:0}}function b(){l.log.apply(l,arguments)}var j={},k={},o=[],A=0,p=
1,v=l.ErrorUtils,q=0,s,D=!1;document.addEventListener?s=function(){document.removeEventListener("DOMContentLoaded",s,!1);c()}:document.attachEvent&&(s=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",s),c())});e.__debug__=j;e.__waiting__=k;document.addEventListener?(document.addEventListener("DOMContentLoaded",s,!1),window.addEventListener("load",c,!1)):document.attachEvent&&(document.attachEvent("onreadystatechange",s),window.attachEvent("onload",c));d("global",
m);d("module",1);d("exports",1);d("require",e);d("requireAsync",a);d("requireLazy",f);m.define=h;m.require=e;m.requireAsync=a;m.requireLazy=f;m.__d=function(a,b,c){return h(a,"global,module,exports,require,requireAsync,requireLazy".split(",").concat(b),c)};m.console||(m.console={log:b,error:b,dir:b})})(window,BigPipe);
__d("common.js.config",[],function(m,l,h){function g(a){var a=a||{},f;for(f in a)a.hasOwnProperty(f)&&(e[f]=a[f]);g=function(){}}var e={};return h={__config__:e,init:g,get:function(a,f){return e.hasOwnProperty(a)?e[a]:f}}});
__d("common.js.events",[],function(m,l,h){function g(a,d){var b=a[0],e=a[1],d=a[2].concat(d);try{return b.apply(e,d)}catch(f){setTimeout(function(){throw f;},0)}}function e(c,d){var b=a[c],e,k;if(!b)return!0;d=f.call(arguments,1);b=b.cbs;e=b.length;for(k=!0;e--;)b[e]&&(k=!1!==g(b[e],d)&&k);return!!k}var a={},f=[].slice;return h={on:function(c,d,b){var e,k,h;if(!(e=a[c]))a[c]=e={args:null,cbs:[]};b=b||m;k=[d,b,f.call(arguments,3)];(h=e.args)?g(k,h):e.cbs.push(k)},un:function(c,d){var b=a[c],e;if(!b)return!0;
if(1==arguments.length)b.cbs=[];else{b=b.cbs;for(e=b.length;e--;)b[e]&&b[e][0]===d&&b.splice(e,1)}},emit:function(a,d){return e.apply(this,arguments)},done:function(c,d){var b,g,h;if(!(b=a[c]))a[c]=b={args:d,cbs:[]};g=b.cbs;h=g.length;d=f.call(arguments,1);b.args=d;e.apply(this,arguments);b.cbs=g.slice(h)},undo:function(c){c=a[c];if(!c)return!1;c.args=null}}});
__d("common.js.pageEvents",["common.js.events"],function(m,l,h,g){function e(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c}function a(){var a={},b;b=null!=window.innerHeight?{width:window.innerWidth,height:window.innerHeight}:"CSS1Compat"==document.compatMode?{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight}:{width:document.body.clientWidth,height:document.body.clientHeight};var c;c=null!=window.pageXOffset?
{scrollLeft:window.pageXOffset,scrollTop:window.pageYOffset}:"CSS1Compat"==document.compatMode?{scrollLeft:document.documentElement.scrollLeft,scrollTop:document.documentElement.scrollTop}:{scrollLeft:document.body.scrollLeft,scrollTop:document.body.scrollTop};a.height=b.height;a.width=b.width;a.scrollLeft=c.scrollLeft;a.scrollTop=c.scrollTop;return a}function f(c,d){var e;e=a();e.originalEvent=c&&c.originalEvent;k?clearTimeout(k):b.emit("viewport.startchange",e);b.emit("viewport.change",e);k=setTimeout(function(){k=
0;e=a();e.originalEvent=c&&c.originalEvent;b.emit("viewport.deferchange",e)},d||20)}function c(a,c){function d(){A=0;b.emit("page.endchange",a)}var c=c||0,e=+new Date+c;A||b.emit("page.startchange",a);b.emit("page.change",a);p<e&&(p=e,c?(clearTimeout(A),A=setTimeout(d,c)):d())}function d(){this.emitViewportChange=f;this.emitPageChange=c;this.getViewport=a}for(var b=g("common.js.events"),m=[[window,"scroll","window.scroll"],[window,"resize","window.resize"]],j,k,l=m.length;l--;){var o,h=m[l],g=h[0];
j=h[1];o=h[2];e(g,j,function(a){b.emit(o,{originalEvent:a})})}var A=0,p=0;b.on("window.scroll",f);b.on("window.resize",f);b.done("window.init",a());d.prototype=b;return h=new d});
__d("common.js.queue",[],function(m,l,h){function g(c,d,b){a.push([c,d,b]);if(!f){for(f=!0;c=a.length;){for(d=0;d<c;d++)b=a[d],b[0].apply(b[1],b[2]);a.splice(0,c)}f=!1}}function e(a,d,b){var f=Array.prototype.slice;e=function(a,b,c){var d=f.call(arguments,1);return f.apply(a,d)};return e.apply(this,e(arguments,0))}var a=[],f=!1;return h={call:function(a,d){return g(a,d,e(arguments,2))},apply:g}});
__d("common.js.lazy",["common.js.pageEvents","common.js.queue"],function(m,l,h,g,e,a){function f(){B==q&&(B=s,a(["common.js.jquery"],function(){B=D;f=c;k.call(f)}))}function c(){var a,c,d;for(a=0,c=o.length;a<c;a++){d=o[a];void 0===d.offsetTop&&d.valid&&(d.offsetTop=b(d.elem));var e;if(e=void 0!==d.offsetTop)d.valid?p.scrollTop+p.height+50>d.offsetTop?(k.call(d.callback,m,d.elem),e=!0):e=!1:e=!0;e&&(o.splice(a,1),a--,c--)}}function d(a){a.setAttribute("src",a.getAttribute("data-src"))}function b(a){var b=
0,c;try{for(;0>=b;){if(!a||!(c=$(a).offset()))return;b=c.top;a=a.parentNode}}catch(d){return}return b}var j=g("common.js.pageEvents"),k=g("common.js.queue"),o=[],A=0,p,v=!1,q=1,s=2,D=3,B=q;j.on("viewport.change",function(){v||(p=j.getViewport(),k.call(f))});j.on("page.endchange",function(){if(!v){for(var a=0,b=o.length;a<b;a++)o[a].offsetTop=void 0;k.call(f)}});return h={add:function(a,b){"length"in a||(a=[a]);for(var c=0,e,g=a.length;c<g;c++)e={elem:a[c],callback:b||d,key:A,valid:!0},o.push(e);p||
(p=j.getViewport());k.call(f);return A++},remove:function(a){for(var b=o.length;b--;)o[b].key===a&&(o[b].valid=!1)},disable:function(){v=!0},enable:function(){v=!1}}});
__d("common.js.bigRender",["common.js.lazy"],function(m,l,h,g){function e(c){var d=document.getElementById(c.id);a(d,"g-bigrender");var b=f.add(d,function(){c.load();c.on("display",function(){if(d){var a=d.className;0!=a.length&&("g-bigrender"==a?d.className="":a.match(/(^|\s)g-bigrender(\s|$)/)&&(d.className=a.replace(/(^|\s)g-bigrender(\s|$)/," ")))}})});c.on("unload",function(){f.remove(b)})}function a(a,d){if(a){var b=a.className;0==b.length?a.className=d:b==d||b.match(RegExp("(^|\\s)"+d+"(\\s|$)"))||
(a.className=b+" "+d)}}var f=g("common.js.lazy");return h={add:function(a){try{if(a.parent)a.parent.on("display",function(){e(a)});else e(a);return!0}catch(d){return setTimeout(function(){throw d;},0),!1}}}});
__d("common.js.load",[],function(m,l,h){var g=document;return h={loadScript:function(e,a,f){a=g.createElement("script");g.getElementsByTagName("head");f=f||{};a.type="text/javascript";a.src=e;var e=a,a=null,c;for(c in f)a=g.createAttribute(c),a.value=f[c],e.setAttributeNode(a);g.body.appendChild(e)},loadScriptString:function(e){var a=g.createElement("script");a.type="text/javascript";try{a.appendChild(g.createTextNode(e))}catch(f){a.text=e}g.body.appendChild(a)},loadStyle:function(){},loadStyleString:function(e){var a=
g.createElement("style"),f=g.getElementsByTagName("head")[0];a.type="text/css";try{a.appendChild(g.createTextNode(e))}catch(c){a.styleSheet.cssText=e}f.appendChild(a)}}});
__d("common.js.format",[],function(){function m(l,h){var g=Array.prototype.slice.call(arguments,1),e=Object.prototype.toString;return g.length?(g=1==g.length?null!==h&&/\[object Array\]|\[object Object\]/.test(e.call(h))?h:g:g,l.replace(/#\{(.+?)\}/g,function(a,f){var c,d,b,h,k;if(!g)return"";c=f.split("|");d=g[c[0]];"[object Function]"==e.call(d)&&(d=d(c[0]));for(b=1,h=c.length;b<h;++b)k=m.filters[c[b]],"[object Function]"==e.call(k)&&(d=k(d));return"undefined"==typeof d||null===d?"":d})):l}m.filters=
{escapeJs:function(l){if(!l||"string"!=typeof l)return l;var h,g,e,a=[];for(h=0,g=l.length;h<g;++h)e=l.charCodeAt(h),255<e?a.push(l.charAt(h)):a.push("\\x"+e.toString(16));return a.join("")},escapeString:function(l){return!l||"string"!=typeof l?l:l.replace(/["'<>\\\/`]/g,function(h){return"&#"+h.charCodeAt(0)+";"})},escapeUrl:function(l){return!l||"string"!=typeof l?l:encodeURIComponent(l)},toInt:function(l){return parseInt(l,10)||0}};m.filters.js=m.filters.escapeJs;m.filters.e=m.filters.escapeString;
m.filters.u=m.filters.escapeUrl;m.filters.i=m.filters.toInt;return m});
__d("common.js.log",["common.js.config"],function(m,l,h,g){function e(a,d){for(var b in d)a[b]=d[b];return a}var a=window,f=g("common.js.config").get("logConf",{level:1,page:"index"});return function(c,d){function b(){a["__logImg_"+h]=null;a["__logImg_"+h]=void 0}var g={},h=c.r=+new Date,l=a["__logImg_"+h]=new Image,m=[],p=d&&d.url||"/images/track.gif",v=d&&d.callback,g=e(g,f),g=e(g,c),q;for(q in g)"thisUrl"!=q&&m.push(encodeURIComponent(q)+"="+encodeURIComponent(g[q]));l.onload=function(){b();v&&
v(!0)};l.onerror=function(){b();v&&v(!1)};l.src=p+"?"+m.join("&");l=m=null}});__d("common.js.hearbeat",["common.js.log"],function(m,l,h,g){var e=g("common.js.log");return function(a,f){function c(){var b={},c;for(c in a)b[c]="[object Function]"==Object.prototype.toString.call(a[c])?a[c]():a[c];e(b);d()}function d(){b++;setTimeout(c,"[object Function]"==Object.prototype.toString.call(f)?f(b):f)}var b=0;d()}});
__d("site.hearbeat",["common.js.hearbeat"],function(m,l,h,g){var e=g("common.js.hearbeat");return function(){var a;0.01>Math.random()&&(a=+new Date,e({type:"heartbeat",sessionid:a,staytime:function(){return+new Date-a}},function(a){var c;c=Math.pow(a-1,2);a=Math.pow(a,2);return 1E3*(c+(a-c)*Math.random())}))}});
__d("common.js.detect",["common.js.log"],function(m,l,h,g){function e(){-1<document.getElementById("_amd").style.display.indexOf("none")&&(a=!0);f.parentNode.removeChild(f);a&&c({type:"detect"},{url:"http://www.hao123.com/images/b.gif"})}var a=!1,f=void 0,c=g("common.js.log");return function(){f=document.createElement("IMG");f.id="_amd";f.src="http://www.hao123.com/adimages/textlink-ads.gif";f.style.width="1px";f.style.height="1px";f.style.top="-1000px";f.style.left="-1000px";document.body.appendChild(f);
setTimeout(e,100)}});__d("common.js.secure",[],function(m,l,h){l.exports.encrypt=function(g){var e,a;if(!g)return!1;e=[];for(a=g.length;a--;)e.push(encodeURIComponent(String.fromCharCode(g.charCodeAt(a)-10)));return e.join("")};l.exports.decrypt=function(g){var e,a;if(!g)return!1;e=[];g=decodeURIComponent(g);for(a=g.length;a--;)e.push(String.fromCharCode(g.charCodeAt(a)+10));return e.join("")};return h});window.js_jAYzvZnRqJ&&window.js_jAYzvZnRqJ(!0);
